from enum import Enum

RED_TEAM_SIZE = 10
BLUE_TEAM_SIZE = 10

MAP_WIDTH = 1000
MAP_HEIGHT = 1000

class FighterActions(Enum):
    FORWARD = 0
    TURN_CCW = 1
    TURN_CW = 2
    FIRE = 3
    RELOAD = 4

FIGHTER_FORWARD_RATE = 3
FIGHTER_ANGLE_RATE = 6
FIGHTER_MAGAZINE_SIZE = 5
FIGHTER_WEAPON_TIMEOUT = 10 # in ticks
FIGHTER_RELOAD_TIME = 60

MISSILE_SPEED = 20
MISSILE_RANGE = 300
